packages:
  - packages/*
  - playground
catalogs:
  tooling:
    tsx: ^4.22.3
    turbo: ^2.9.15
    typescript: ^6.0.3
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plus: latest
  testing:
    vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue:
    vue: ^3.5.35
    '@vitejs/plugin-vue': ^6.0.7
    '@vue/tsconfig': ^0.9.1
    vue-tsc: ^3.3.2
  types:
    '@types/node': ^26.0.1
overrides:
  vite: 'catalog:tooling'
  vitest: 'catalog:testing'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
